import SwiftUI

class MotivationData: ObservableObject {
    @Published var motivationalWords: [String] = [
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
        "The only way to achieve the impossible is to believe it is possible.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "Don’t watch the clock; do what it does. Keep going.",
        "You are never too old to set another goal or to dream a new dream.",
        "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "It's not whether you get knocked down, it's whether you get up.",
        "Success usually comes to those who are too busy to be looking for it.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Believe you can and you're halfway there.",
        "Strive not to be a success, but rather to be of value.",
        "You miss 100% of the shots you don't take.",
        "Success is stumbling from failure to failure with no loss of enthusiasm.",
        "The only place where success comes before work is in the dictionary.",
        "Don't be afraid to give up the good to go for the great.",
        "If you want to achieve greatness stop asking for permission.",
        "I find that the harder I work, the more luck I seem to have.",
        "There is no substitute for hard work.",
        "Your only limit is you.",
        "Dream big, work hard, stay focused.",
        "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
        "The best way to predict the future is to create it.",
        "Don't wait for opportunity, create it.",
        "Your time is now. Start where you are, use what you have, do what you can.",
        "The only person you are destined to become is the person you decide to be.",
        "Believe in your dreams, they were given to you for a reason.",
        "Strive for progress, not perfection.",
        "You are stronger than you think.",
        "Every day may not be good, but there is something good in every day.",
        "Do it with passion or not at all.",
        "The difference between a stumbling block and a stepping stone is how high you raise your foot.",
        "Your life does not get better by chance, it gets better by change.",
        "You have within you right now, everything you need to deal with whatever the world can throw at you.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Every accomplishment starts with the decision to try.",
        "Success is not in what you have, but who you are.",
        "The only way to do great work is to love what you do.",
        "Don't let the fear of losing be greater than the excitement of winning.",
        "Your only limit is you.",
        "Dream big, work hard, stay focused.",
        "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
        "The best way to predict the future is to create it.",
        "Don't wait for opportunity, create it.",
        "Your time is now. Start where you are, use what you have, do what you can.",
        "The only person you are destined to become is the person you decide to be.",
        "Believe in your dreams, they were given to you for a reason.",
        "Strive for progress, not perfection.",
        "You are stronger than you think.",
        "Every day may not be good, but there is something good in every day.",
        "Do it with passion or not at all.",
        "The difference between a stumbling block and a stepping stone is how high you raise your foot.",
        "Your life does not get better by chance, it gets better by change.",
        "You have within you right now, everything you need to deal with whatever the world can throw at you.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Every accomplishment starts with the decision to try.",
        "Success is not in what you have, but who you are.",
        "The only way to do great work is to love what you do.",
        "Don't let the fear of losing be greater than the excitement of winning.",
        "The only place where success comes before work is in the dictionary.",
        "If you want to achieve greatness stop asking for permission.",
        "I find that the harder I work, the more luck I seem to have.",
        "There is no substitute for hard work."
    ]
}
